In [1]:
import structure_prediction
from importlib import reload
reload(structure_prediction)
data_folder = './'
structure_prediction.main(data_folder)

evolutionary shape= (5376,)
id shape= (1,)
primary shape= (256,)
tertiary shape= (256, 3)
primary_onehot shape= (256, 21)
mask shape= (256,)
true_distances shape= (256, 256)
distance_mask shape= (256, 256)
Value info of one data record, structure: tf.Tensor([1806.5  322.7 6882.9], shape=(3,), dtype=float32)
evolutionary shape= (5376,)
id shape= (1,)
primary shape= (256,)
tertiary shape= (256, 3)
primary_onehot shape= (256, 21)
mask shape= (256,)
true_distances shape= (256, 256)
distance_mask shape= (256, 256)
Value info of one data record, structure: tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
evolutionary shape= (5376,)
id shape= (1,)
primary shape= (256,)
tertiary shape= (256, 3)
primary_onehot shape= (256, 21)
mask shape= (256,)
true_distances shape= (256, 256)
distance_mask shape= (256, 256)
Value info of one data record, structure: tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
Start of epoch 0
<dtype: 'float32'>
<dtype: 'float32'>
<dtype: 'float32'>
<dtype: 'float32'>


KeyboardInterrupt: 